import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { pipeline } from 'node:stream/promises';
import cors from 'cors';
import express, { type NextFunction, type Request, type Response } from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import morgan from 'morgan';
import multer from 'multer';
import { z } from 'zod';
import { config } from './config.js';
import { db } from './db.js';
import { accessToken, error, hashPassword, playbackToken, requireAdmin, requireAuth, verifyPassword } from './security.js';
import { validate } from './validate.js';

const id=z.object({id:z.string().uuid()}); const now=()=>new Date().toISOString();
const movieBody=z.object({title:z.string().trim().min(1).max(200),description:z.string().max(5000).default(''),year:z.number().int().min(1888).max(2200).nullable().optional(),genres:z.array(z.string().min(1).max(50)).max(20).default([]),contentRating:z.string().max(20).nullable().optional()});
const uploadBody=z.object({movieId:z.string().uuid(),fileName:z.string().min(1).max(255),fileSize:z.number().int().positive().max(1024**4),mimeType:z.enum(['video/mp4','video/x-matroska','video/webm']),sha256:z.string().regex(/^[a-f0-9]{64}$/i).optional()});
const disk=(dir:string)=>multer.diskStorage({destination:dir,filename:(_r,file,cb)=>cb(null,`${crypto.randomUUID()}${path.extname(file.originalname).toLowerCase()}`)});
const poster=multer({storage:disk(config.posterDir),limits:{fileSize:config.MAX_POSTER_BYTES},fileFilter:(_r,f,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(f.mimetype))});
const tokenHash=(token:string)=>crypto.createHash('sha256').update(token).digest('hex');
function issueRefresh(userId:string){const token=crypto.randomBytes(48).toString('base64url'),stamp=now(),expiresAt=new Date(Date.now()+config.REFRESH_TOKEN_TTL_DAYS*86400_000).toISOString();db.prepare('INSERT INTO refresh_tokens VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),userId,tokenHash(token),expiresAt,null,stamp);return token;}

export const app=express(); app.disable('x-powered-by'); app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:config.CORS_ORIGINS==='*'?'*':config.CORS_ORIGINS.split(',')}));
app.use((req,_res,next)=>{req.requestId=crypto.randomUUID();next();}); morgan.token('id',req=>(req as Request).requestId); app.use(morgan(':id :method :url :status :response-time ms',{skip:req=>req.url.includes('token=')})); app.use(express.json({limit:'1mb'}));
app.get('/api/v1/health',(_req,res)=>res.json({data:{ok:true,version:'1.0.0',database:'connected',uptimeSeconds:Math.floor(process.uptime())}}));

app.post('/api/v1/auth/login',rateLimit({windowMs:15*60_000,limit:10,standardHeaders:true,legacyHeaders:false}),validate(z.object({username:z.string().min(1),password:z.string().min(8)})),async(req,res)=>{const user=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(req.body.username) as any;if(!user||!await verifyPassword(req.body.password,user.password_hash))return res.status(401).json(error('INVALID_CREDENTIALS','Usuario o contraseña incorrectos.',req.requestId));const auth={sub:user.id,username:user.username,role:user.role};res.json({data:{accessToken:accessToken(auth),refreshToken:issueRefresh(user.id),user:{id:user.id,username:user.username,displayName:user.display_name,role:user.role}}});});
app.post('/api/v1/auth/refresh',validate(z.object({refreshToken:z.string().min(20)})),(req,res)=>{const hash=tokenHash(req.body.refreshToken),row=db.prepare('SELECT rt.id AS refresh_id,u.id AS user_id,u.username,u.role FROM refresh_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=? AND rt.revoked_at IS NULL AND rt.expires_at>? AND u.active=1').get(hash,now()) as any;if(!row)return res.status(401).json(error('REFRESH_TOKEN_INVALID','Sesión inválida o vencida.',req.requestId));db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE id=?').run(now(),row.refresh_id);const auth={sub:row.user_id,username:row.username,role:row.role};res.json({data:{accessToken:accessToken(auth),refreshToken:issueRefresh(row.user_id)}});});
app.post('/api/v1/auth/logout',validate(z.object({refreshToken:z.string().min(20)})),(req,res)=>{db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE token_hash=? AND revoked_at IS NULL').run(now(),tokenHash(req.body.refreshToken));res.status(204).end();});
app.post('/api/v1/auth/logout-all',requireAuth,(req,res)=>{db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').run(now(),req.user!.sub);res.status(204).end();});
app.get('/api/v1/auth/me',requireAuth,(req,res)=>res.json({data:req.user}));

app.get('/api/v1/admin/users',requireAuth,requireAdmin,(_req,res)=>res.json({data:db.prepare('SELECT id,username,display_name AS displayName,role,active,created_at AS createdAt FROM users ORDER BY created_at DESC').all()}));
app.post('/api/v1/admin/users',requireAuth,requireAdmin,validate(z.object({username:z.string().regex(/^[a-zA-Z0-9_.-]{3,40}$/),displayName:z.string().min(1).max(100),password:z.string().min(8).max(200),role:z.enum(['admin','viewer']).default('viewer')})),async(req,res)=>{const userId=crypto.randomUUID();try{db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run(userId,req.body.username,req.body.displayName,await hashPassword(req.body.password),req.body.role,1,now());res.status(201).json({data:{id:userId,username:req.body.username,role:req.body.role}});}catch{res.status(409).json(error('USERNAME_EXISTS','El usuario ya existe.',req.requestId));}});

app.get('/api/v1/movies',requireAuth,(req,res)=>{const q=z.object({page:z.coerce.number().int().positive().default(1),limit:z.coerce.number().int().min(1).max(100).default(20),search:z.string().default('')}).parse(req.query);const where=req.user?.role==='admin'?"status!='error'":"status='published'";const items=db.prepare(`SELECT * FROM movies WHERE ${where} AND title LIKE ? ORDER BY created_at DESC LIMIT ? OFFSET ?`).all(`%${q.search}%`,q.limit,(q.page-1)*q.limit);res.json({data:items.map(mapMovie),meta:{page:q.page,limit:q.limit}});});
app.get('/api/v1/movies/:id',requireAuth,validate(id,'params'),(req,res)=>{const row=db.prepare('SELECT * FROM movies WHERE id=?').get(req.params.id) as any;if(!row||row.status!=='published'&&req.user?.role!=='admin')return res.status(404).json(error('MOVIE_NOT_FOUND','Película no encontrada.',req.requestId));res.json({data:mapMovie(row)});});
app.post('/api/v1/admin/movies',requireAuth,requireAdmin,validate(movieBody), (req,res)=>{const movieId=crypto.randomUUID(),stamp=now();db.prepare('INSERT INTO movies(id,title,description,year,genres_json,content_rating,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(movieId,req.body.title,req.body.description,req.body.year??null,JSON.stringify(req.body.genres),req.body.contentRating??null,'draft',stamp,stamp);res.status(201).json({data:{id:movieId,...req.body,status:'draft'}});});
app.patch('/api/v1/admin/movies/:id',requireAuth,requireAdmin,validate(id,'params'),validate(movieBody.partial()),(req,res)=>{const current=db.prepare('SELECT * FROM movies WHERE id=?').get(req.params.id) as any;if(!current)return res.status(404).json(error('MOVIE_NOT_FOUND','Película no encontrada.',req.requestId));const next={title:req.body.title??current.title,description:req.body.description??current.description,year:req.body.year??current.year,genres:req.body.genres??JSON.parse(current.genres_json),rating:req.body.contentRating??current.content_rating};db.prepare('UPDATE movies SET title=?,description=?,year=?,genres_json=?,content_rating=?,updated_at=? WHERE id=?').run(next.title,next.description,next.year,JSON.stringify(next.genres),next.rating,now(),req.params.id);res.json({data:{id:req.params.id,...next}});});
app.post('/api/v1/admin/movies/:id/publish',requireAuth,requireAdmin,validate(id,'params'),(req,res)=>{const result=db.prepare("UPDATE movies SET status='published',updated_at=? WHERE id=? AND video_path IS NOT NULL").run(now(),req.params.id);if(!result.changes)return res.status(409).json(error('VIDEO_REQUIRED','La película necesita un video.',req.requestId));res.json({data:{id:req.params.id,status:'published'}});});
app.post('/api/v1/admin/movies/:id/unpublish',requireAuth,requireAdmin,validate(id,'params'),(req,res)=>{db.prepare("UPDATE movies SET status='hidden',updated_at=? WHERE id=?").run(now(),req.params.id);res.json({data:{id:req.params.id,status:'hidden'}});});
app.post('/api/v1/admin/movies/:id/poster',requireAuth,requireAdmin,validate(id,'params'),poster.single('poster'),(req,res)=>{if(!req.file)return res.status(400).json(error('INVALID_POSTER','Portada inválida.',req.requestId));db.prepare('UPDATE movies SET poster_path=?,updated_at=? WHERE id=?').run(req.file.path,now(),req.params.id);res.status(201).json({data:{fileName:path.basename(req.file.path)}});});
app.get('/api/v1/movies/:id/poster',requireAuth,validate(id,'params'),(req,res)=>{const row=db.prepare('SELECT poster_path FROM movies WHERE id=?').get(req.params.id) as any;if(!row?.poster_path)return res.status(404).end();res.sendFile(row.poster_path);});

app.post('/api/v1/admin/uploads',requireAuth,requireAdmin,validate(uploadBody),(req,res)=>{const movie=db.prepare('SELECT id FROM movies WHERE id=?').get(req.body.movieId);if(!movie)return res.status(404).json(error('MOVIE_NOT_FOUND','Película no encontrada.',req.requestId));const uploadId=crypto.randomUUID(),temp=path.join(config.uploadDir,`${uploadId}.part`),stamp=now(),expires=new Date(Date.now()+48*3600_000).toISOString();fs.closeSync(fs.openSync(temp,'wx'));db.prepare('INSERT INTO uploads VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(uploadId,req.body.movieId,path.basename(req.body.fileName),temp,req.body.fileSize,0,req.body.mimeType,req.body.sha256??null,'pending',expires,stamp,stamp);db.prepare("UPDATE movies SET status='uploading',updated_at=? WHERE id=?").run(stamp,req.body.movieId);res.status(201).json({data:{uploadId,offset:0,chunkSize:config.UPLOAD_CHUNK_BYTES,expiresAt:expires}});});
app.head('/api/v1/admin/uploads/:id',requireAuth,requireAdmin,validate(id,'params'),(req,res)=>{const u=db.prepare('SELECT * FROM uploads WHERE id=?').get(req.params.id) as any;if(!u)return res.status(404).end();res.set({'Upload-Offset':String(u.received_bytes),'Upload-Length':String(u.expected_size),'Upload-Expires':u.expires_at}).status(204).end();});
app.patch('/api/v1/admin/uploads/:id',requireAuth,requireAdmin,validate(id,'params'),async(req,res,next)=>{try{const u=db.prepare("SELECT * FROM uploads WHERE id=? AND status='pending'").get(req.params.id) as any;if(!u)return res.status(404).json(error('UPLOAD_NOT_FOUND','Subida no encontrada.',req.requestId));const offset=Number(req.header('Upload-Offset')),length=Number(req.header('Content-Length'));if(!Number.isSafeInteger(offset)||offset!==u.received_bytes)return res.status(409).json(error('INVALID_UPLOAD_OFFSET','Offset incorrecto.',req.requestId,{expected:u.received_bytes}));if(!Number.isSafeInteger(length)||length<1||length>config.UPLOAD_CHUNK_BYTES||offset+length>u.expected_size)return res.status(413).json(error('INVALID_CHUNK_SIZE','Fragmento inválido.',req.requestId));let received=0;req.on('data',chunk=>{received+=chunk.length;if(received>length)req.destroy(new Error('Chunk exceeds Content-Length'));});await pipeline(req,fs.createWriteStream(u.temporary_path,{flags:'r+',start:offset}));if(received!==length)throw new Error('Incomplete chunk');const nextOffset=offset+received;db.prepare('UPDATE uploads SET received_bytes=?,updated_at=? WHERE id=?').run(nextOffset,now(),u.id);res.set('Upload-Offset',String(nextOffset)).status(204).end();}catch(e){next(e);}});
app.post('/api/v1/admin/uploads/:id/complete',requireAuth,requireAdmin,validate(id,'params'),async(req,res,next)=>{try{const u=db.prepare("SELECT * FROM uploads WHERE id=? AND status='pending'").get(req.params.id) as any;if(!u)return res.status(404).json(error('UPLOAD_NOT_FOUND','Subida no encontrada.',req.requestId));if(u.received_bytes!==u.expected_size)return res.status(409).json(error('UPLOAD_INCOMPLETE','La subida no está completa.',req.requestId));if(u.sha256_expected){const hash=crypto.createHash('sha256');await pipeline(fs.createReadStream(u.temporary_path),hash as any);if(hash.digest('hex')!==u.sha256_expected)return res.status(422).json(error('CHECKSUM_MISMATCH','La verificación SHA-256 falló.',req.requestId));}const ext=path.extname(u.file_name).toLowerCase()||'.mp4',dest=path.join(config.videoDir,`${u.movie_id}${ext}`);fs.renameSync(u.temporary_path,dest);const stamp=now();db.exec('BEGIN');try{db.prepare("UPDATE uploads SET status='completed',updated_at=? WHERE id=?").run(stamp,u.id);db.prepare("UPDATE movies SET video_path=?,mime_type=?,file_size=?,status='hidden',updated_at=? WHERE id=?").run(dest,u.mime_type,u.expected_size,stamp,u.movie_id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}res.json({data:{movieId:u.movie_id,fileSize:u.expected_size,status:'hidden'}});}catch(e){next(e);}});

app.post('/api/v1/movies/:id/playback-token',requireAuth,validate(id,'params'),(req,res)=>{const movieId=String(req.params.id);const m=db.prepare("SELECT id FROM movies WHERE id=? AND status='published' AND video_path IS NOT NULL").get(movieId);if(!m)return res.status(404).json(error('MOVIE_NOT_FOUND','Película no encontrada.',req.requestId));const token=playbackToken(req.user!.sub,movieId);res.json({data:{streamUrl:`/api/v1/movies/${movieId}/stream?token=${token}`,token}});});
app.get('/api/v1/movies/:id/stream',validate(id,'params'),(req,res)=>{try{const payload=jwt.verify(String(req.query.token??''),config.JWT_PLAYBACK_SECRET) as any;if(payload.movieId!==req.params.id||payload.scope!=='playback')throw new Error();}catch{return res.status(401).end();}const m=db.prepare("SELECT video_path,mime_type FROM movies WHERE id=? AND status='published'").get(req.params.id) as any;if(!m?.video_path||!fs.existsSync(m.video_path))return res.status(404).end();const size=fs.statSync(m.video_path).size,range=req.headers.range;res.set({'Accept-Ranges':'bytes','Cache-Control':'private, no-store','Content-Type':m.mime_type??'video/mp4'});if(!range){res.set('Content-Length',String(size));return fs.createReadStream(m.video_path).pipe(res);}const match=/^bytes=(\d*)-(\d*)$/.exec(range);if(!match)return res.status(416).set('Content-Range',`bytes */${size}`).end();let start=match[1]?Number(match[1]):0,end=match[2]?Number(match[2]):size-1;if(!match[1]&&match[2])start=Math.max(0,size-Number(match[2])),end=size-1;if(start>end||start>=size)return res.status(416).set('Content-Range',`bytes */${size}`).end();end=Math.min(end,size-1);res.status(206).set({'Content-Range':`bytes ${start}-${end}/${size}`,'Content-Length':String(end-start+1)});fs.createReadStream(m.video_path,{start,end}).pipe(res);});

app.put('/api/v1/movies/:id/progress',requireAuth,validate(id,'params'),validate(z.object({positionSeconds:z.number().min(0),durationSeconds:z.number().positive(),completed:z.boolean().default(false)})),(req,res)=>{db.prepare('INSERT INTO playback_progress VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,movie_id) DO UPDATE SET position_seconds=excluded.position_seconds,duration_seconds=excluded.duration_seconds,completed=excluded.completed,updated_at=excluded.updated_at').run(req.user!.sub,req.params.id,req.body.positionSeconds,req.body.durationSeconds,req.body.completed?1:0,now());res.json({data:{movieId:req.params.id,...req.body}});});
app.get('/api/v1/me/progress',requireAuth,(req,res)=>res.json({data:db.prepare('SELECT * FROM playback_progress WHERE user_id=? ORDER BY updated_at DESC').all(req.user!.sub)}));
app.post('/api/v1/movies/:id/favorite',requireAuth,validate(id,'params'),(req,res)=>{db.prepare('INSERT OR IGNORE INTO favorites VALUES(?,?,?)').run(req.user!.sub,req.params.id,now());res.status(201).json({data:{movieId:req.params.id,favorite:true}});});
app.delete('/api/v1/movies/:id/favorite',requireAuth,validate(id,'params'),(req,res)=>{db.prepare('DELETE FROM favorites WHERE user_id=? AND movie_id=?').run(req.user!.sub,req.params.id);res.status(204).end();});
app.get('/api/v1/me/favorites',requireAuth,(req,res)=>res.json({data:db.prepare('SELECT m.* FROM favorites f JOIN movies m ON m.id=f.movie_id WHERE f.user_id=?').all(req.user!.sub).map(mapMovie)}));

app.use((_req,res)=>res.status(404).json(error('NOT_FOUND','Ruta no encontrada.',crypto.randomUUID())));app.use((err:unknown,req:Request,res:Response,_next:NextFunction)=>{console.error(req.requestId,err);res.status(500).json(error('INTERNAL_ERROR','Error interno del servidor.',req.requestId));});
function mapMovie(row:any){return{id:row.id,title:row.title,description:row.description,year:row.year,durationSeconds:row.duration_seconds,genres:JSON.parse(row.genres_json),contentRating:row.content_rating,status:row.status,fileSize:row.file_size,posterUrl:`/api/v1/movies/${row.id}/poster`};}
